x

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,3 +1,25 @@
 #!/bin/bash
-echo 'PATH="$HOME/bin/applications/desynchronizer:$PATH"' >> "$HOME/.bashrc"
-echo "Installation successful!"
+
+set -uo pipefail -o noclobber -o nounset
+#set -euxo pipefail
+shopt -s inherit_errexit
+#set -x
+
+handle_error() {
+	# @source https://gist.github.com/bkahlert/08f9ec3b8453db5824a0aa3df6a24cb4
+	local esc_red esc_reset; esc_red=$(tput setaf 1 || true); esc_reset=$(tput sgr0 || true)
+	printf "%s %s\n\tin program:\t %s\n\tat location:\t %s\n\tat line:\t %s\n" "${esc_red-}✘${esc_reset-}" "${esc_red-}$(errno "$1" )${esc_reset-}" "${0##*/}"  "$3" "$2" >&2
+	exit "$1"
+}
+
+trap 'handle_error "$?" "${BASH_COMMAND:-?}" "${FUNCNAME[0]:-main}(${BASH_SOURCE[0]:-?}:${LINENO:-?})"' ERR
+#trap 'echo Program failed! Error at line $LINENO' ERR
+
+sudo apt install moreutils
+
+mkdir --parents "$HOME/applications"
+echo 'source -- "$HOME/applications/desynchronizer/configuration/aliases"' >> "$HOME/.bash_aliases"
+echo 'PATH="$HOME/applications/desynchronizer/bin:$PATH"' >> "$HOME/.bashrc"
+
+set +x
+echo -ne "\n\nSUCCESS!\n\n"
